/** For all Employees **/
export const REQUEST_EMPLOYEES = 'REQUEST_EMPLOYEES'
export const RECEIVE_EMPLOYEES = 'RECEIVE_EMPLOYEES'
/** For Single EMPLOYEE **/
export const REQUEST_EMPLOYEE = 'REQUEST_EMPLOYEE'
export const RECEIVE_EMPLOYEE = 'RECEIVE_EMPLOYEE'
/** Add EMPLOYEE **/
export const REQUEST_EMPLOYEE_ADD = 'REQUEST_EMPLOYEE_ADD'
export const RECEIVE_EMPLOYEE_ADD = 'RECEIVE_EMPLOYEE_ADD'
/** delete EMPLOYEE **/
export const REQUEST_EMPLOYEE_DELETE = 'REQUEST_EMPLOYEE_DELETE'
export const RECEIVE_EMPLOYEE_DELETE = 'RECEIVE_EMPLOYEE_DELETE'
/** UPADTE EMPLOYEE **/
export const REQUEST_EMPLOYEE_UPADTE = 'REQUEST_EMPLOYEE_UPADTE'
export const RECEIVE_EMPLOYEE_UPADTE = 'RECEIVE_EMPLOYEE_UPADTE'
